# Generated by Django 2.2.28 on 2022-10-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressuqqvuwcarj'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressuqqvuwcarj',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
